language: python

script:
  - echo "no tests"
  - pwd

addons:
  apt:
    packages:
    - sshpass

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  # script: echo "test deploy"
  on:
    branch: master
