language: python

addons:
  apt:
    packages:
    - sshpass

deploy:
  - provider: script
    skip_cleanup: true
    script: sshpass -e ssh pi@kettle.mur-phy.com "supervisorctl restart kettlr"
    on:
      branch: master

script:
  - echo "no tests"
