language: python

addons:
  apt:
    packages:
    - sshpass

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master

script:
  - echo "no tests"
