language: python

script:
  - echo "no tests"

addons:
  apt:
    packages:
    - sshpass

deploy:
  provider: script
  skip_cleanup: true
  # script: sshpass -e ssh pi@kettle.mur-phy.com "supervisorctl restart kettlr"
  script: echo "test deploy"
  on:
    branch: master
