language: python

addons:
  apt:
    packages:
    - sshpass

deploy:
  skip_cleanup: true
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master

script:
  - echo "no tests"
